### ISSUE TITLE
TextCaps json file missing for TextVQA

### ISSUE THREAD

**Issue by HenryJunW** [microsoft/TAP#11]
Hello, I would like to train the TextVQA model with the extra data of TextCaps, however, the file 'TextCaps_0.1_train.json' is not provided in Line https://github.com/microsoft/TAP/blob/352891f93c75ac5d6b9ba141bbe831477dcdd807/pythia/datasets/vqa/m4c_textvqa/dataset.py#L36. Thanks!

**Comment by HenryJunW** [comment]
Is that the same from the official website https://dl.fbaipublicfiles.com/textvqa/data/textcaps/TextCaps_0.1_train.json?

**Comment by zyang-ur** [comment]
Hi @HenryJunW,

Thank you so much for catching this!

Yes, your understanding is correct. I also uploaded the missing files (https://tapvqacaption.blob.core.windows.net/data/original_dl/TextCaps_0.1_train.json), feel free to have a check. Thank you :)
