### ISSUE TITLE
VQA output

### ISSUE THREAD

**Issue by abhinavkcs11** [microsoft/TAP#16]
Is it possible to visualize the output of the vqa and captioning i.e. what answers/captions models are producing?

**Comment by zyang-ur** [comment]
Hi @abhinavkcs11 

The evalai flag (https://github.com/microsoft/TAP/blob/352891f93c75ac5d6b9ba141bbe831477dcdd807/pythia/utils/flags.py#L143) should be able to save predictions as a file.
