### ISSUE TITLE
About the number of OCR in stvqa dataset

### ISSUE THREAD

**Issue by JayZhu0104** [microsoft/TAP#4]
Hi！
I found that the number of words detected by OCR in some pictures in stvqa dataset is inconsistent with the corresponding feature number. 
For example, the number of features in 'feat_resx/stvqa/train/imageNet/n03196217_ 7957. npy' is 33, while the number of OCR words in the corresponding 'ocr_ feat_ resx/stvqa_ conf/train/imageNet/n03196217_ 7957_info. npy' is 55. The two numbers do not match. About 2000 pictures have this problem in train dataset.
![image](https://user-images.githubusercontent.com/40751213/134791864-c67e68e6-53f4-453a-a184-1747649049a3.png)

**Comment by zyang-ur** [comment]
Updated the corresponded files :)
